//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5thSemesterProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Log
    {


        public Log()
        {

        }

        public Log(string employee_name, string action, DateTime timestamp)
        {
            this.employee_name = employee_name;
            this.action = action;
            this.timestamp = timestamp;
        }

        public int log_id { get; set; }
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string action { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}